- composer.json
- config/providers.php
- src/WidgetFactoryProvider.php
> Add factory auto initialize

- README.md
> Fix badged README.md.

- composer.json
- src/Widget.php
> Make widgets not encodable

- src/Widget.php
- src/WidgetFactory.php
- tests/WidgetTest.php
Merge after https://github.com/yiisoft/factory/pull/78
> Adopt configs to new factory syntax

- README.md
- src/Widget.php
> Add description to readme, improve throwing exceptions

- src/WidgetFactory.php
Adopt to https://github.com/yiisoft/factory/pull/103
> Adopt to remove FactoryInterface from yiisoft/factory

- src/WidgetFactory.php
> Use composition instead of inheritance in `WidgetFactory` and add parameter `validate`  to `WidgetFactory::initialize()`

- composer.json
- src/Widget.php
- src/WidgetFactory.php
> Adopt to `yiisoft/definitions`

- composer.json
> Add support `psr/container` ^2.0

- composer.json
- config/bootstrap.php
- config/params.php
> Add params for configure `WidgetFactory`

- composer.json
> Use stable yiisoft/definitions package

- src/WidgetFactory.php
> Fix static analysis for WidgetFactory

- src/Widget.php
- src/WidgetFactory.php
> Make container mandatory for widget factory

- CHANGELOG.md
- src/WidgetFactoryInitializationException.php
> Fix solution description to WidgetFactoryInitializationException

- tests/WidgetTest.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
> Separate chain calls

- CHANGELOG.md
- composer.json
> Add support for `yiisoft/definitions` version `^3.0`

- CHANGELOG.md
- composer.json
> Add support for `yiisoft/html` version `^3.0`

- CHANGELOG.md
- src/WidgetFactoryInitializationException.php
> Fix typo in `WidgetFactoryInitializationException` solution

- README.md
> Fix accidental readme changes

- README.md
> Fix accidental readme changes 2

- CHANGELOG.md
- src/Widget.php
- tests/Stubs/Car.php
- tests/WidgetTest.php
> Allow to merge config and constructor arguments

- UPGRADE.md
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Add upgrade instructions

- CHANGELOG.md
- composer.json
- psalm.xml
- src/Widget.php
- tests/WidgetTest.php
> Fix merge constructor arguments with array definition configuration into `Widget::widget()`

- CHANGELOG.md
- src/Widget.php
Example of usage: https://github.com/yiisoft/form/pull/244
> Add default widget config

- CHANGELOG.md
- README.md
- composer.json
- config/bootstrap.php
- config/params.php
- config/widgets.php
- docs/guide/en/README.md
- docs/guide/en/themes.md
- docs/guide/en/widget-configuring.md
- docs/guide/en/widget-for-capturing-content.md
- docs/internals.md
- src/Widget.php
- src/WidgetFactory.php
- src/WidgetFactoryInitializationException.php
- tests/Stubs/Table.php
- tests/ThemeTest.php
- tests/WidgetFactoryTest.php
- tests/WidgetTest.php
> Add widget themes

- CHANGELOG.md
- config/bootstrap.php
- config/params.php
- psalm.xml
- src/WidgetFactory.php
- tests/ThemeTest.php
- tests/WidgetFactoryTest.php
> Add ability to set default theme for concrete widget

- .github/workflows/build.yml
- .github/workflows/composer-require-checker.yml
- .github/workflows/mutation.yml
- .github/workflows/rector.yml
- .github/workflows/static.yml
- CHANGELOG.md
- composer.json
- src/NotInstantiableException.php
- src/NotInstantiableWithoutWidgetFactoryInitializationException.php
- src/WidgetFactory.php
- src/WidgetFactoryInitializationException.php
- tests/Stubs/Garage.php
- tests/WidgetTest.php
> Allow use widgets without widget factory initialization + Improve CI

- docs/guide/en/README.md
- docs/guide/pt-BR/README.md
- docs/guide/pt-BR/themes.md
- docs/guide/pt-BR/widget-configuring.md
- docs/guide/pt-BR/widget-for-capturing-content.md
- psalm.xml
Note the following:
- created folders according to the standard for documentation
- all links checked
> Translation into Brazilian Portuguese and corrections to docs in English
